### ISSUE TITLE
Tooltip is missing if I set both image and name in initialization

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-avatar#55] opened 2020-08-12 05:45 UTC
I have the following code in my Vaadin Java app.

```java
String userName = "Anonymous User";
String userAvatar = "images/avatars/1.png";
avatar = new Avatar(userName, userAvatar);
layout.add(avatar);
```

And with it I get the following view
![Screenshot 2020-08-12 at 8 38 35](https://user-images.githubusercontent.com/525503/89979139-b559c680-dc77-11ea-877d-1c12c63fd923.png)

Component and image is working fine, it also has the name property in the dom, but title property is missing. That leads to no tooltip when you hover it. If I remove the image and instead call 

```java
avatar = new Avatar(userName);
```

![Screenshot 2020-08-12 at 8 43 27](https://user-images.githubusercontent.com/525503/89979242-f4881780-dc77-11ea-9862-c2232aa8dd71.png)

Now the title is there present and working like expected.

I know this is Java code in the web component repo, but the missing `title=""` felt to me like it is a problem in the web component, so I posted here.

**Comment by pekam** [comment] 2020-08-12 06:02
Duplicate of #50 which is fixed but not yet released.

**Closed as completed by pekam** 2020-08-12 06:02 UTC
